# Site settings
title: Space Exploration and Research Association
description: Those who push the new horizons
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SERA
user_description: An association of DTU students who are keen to develop and build tech for space exploration and research purposes.
user_title: Beyond the horizons
email: vermakashish888@gmail.com
twitter_username: 
github_username: iamkashish 
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
